### ISSUE TITLE
sketchup doesn't load the extension on mac

### ISSUE THREAD

**Issue by aravosprec** [JoakimSoderberg/sketchup-svg-outline-plugin#3]
I used your version of FlightOfIdeas extension  (and thanks for taking care of it)  with SU 2015 on Windows, but I couldn't make it work on MacOSX (Yosemite). Do you know if other user had the same issue? Do you have an idea about what the problem might be?

**Comment by tossedman** [comment]
I have the same issue. Is this due to downloading the zip file and renaming it a an rbz file? Is it possible to directly download the rbi file rather than a zip file? Or actually compress the rbz file?

**Comment by JoakimSoderberg** [comment]
Hello, sorry I had missed this question originally since I was on vacation.

@tossedman No, an `.rbz` file IS a zip file, except that it has a different extension. A lot of file formats are like that, `.docx` for Microsoft Word as an example. You can unpack it manually like any other zip file. Sketchup unzips it when installing.

@aravosprec Exactly what steps have you tried? Have you read this http://help.sketchup.com/en/article/38583 ? ... I have tested it on OSX Yosemite and it loads fine for me at least. I'd need more specifics. Any errors at all? Is the extension just not visible in the preferences dialog?

Make sure the plugin is in this directory:

> Mac OS X - the default location is:
> 
> Version 2013 and newer: Open a new Finder window, press and hold the Option key on your keyboard, the click Go in the menu bar > Library > Application Support > SketchUp # > SketchUp > Plugins

`#` in your case would be 2015

In that folder you should have a **flightofideas.rb** and a directory **FlightOfIdeas** containing a bunch of files. You can even unzip manually and place it there yourself.

**Comment by tossedman** [comment]
I got it to work. I installed the downloaded file after changing the extension to .rbz. I then manually removed the FlightOfIdeas files from the sketchup-svg-outline-plugin folder that was in the Library > Application Support > SketchUp 2015 > SketchUp > Plugins folder and manually put them in to Plugins folder. I still didn't see the plugin so I restarted the computer and then had to go into the SketchUp preferences and select the FlightOfIdeas extension. It now works great! Thanks for going through the effort to make it so!

**Comment by JoakimSoderberg** [comment]
@tossedman Ok, great! Yea sketchup is quite finicky sometimes. No clean way to wipe and reinstall without doing it manually. That's why I added those help articles to the README

@aravosprec Try the steps @tossedman described and reopen this if it does not work.
